@startuml

'actor Navbar'
actor Utilizator

Utilizator-->  (se afiseaza un Homepage care contine leaderboard , Navbar si Formular log in / sign up) :acceseaza link site

 Utilizator --> (introduce datele sale in campul de “username” si campul “password” )
 Utilizator  --> (Datele introduse sunt verificate automat intr-un database) :Click pe log in
 (Datele introduse sunt verificate automat intr-un database) --> (Verificarea datelor Permite accesul)
  (Datele introduse sunt verificate automat intr-un database) --> (Verificarea a esuat si nu permite accesul)
(Verificarea datelor Permite accesul) --> (Sunt deblocate features precum locul sau in leaderboard ,ultima sesiune de sport a utilizatorului "View last session" \n, si optiunea de a incepe o sesiune noua de alergat "start new session")
 (Verificarea a esuat si nu permite accesul) --> ( Pagina returneaza mesajul "username or password incorrect, please try again")


Utilizator --> (se va  afisa un pop-up cu statisticile despre ultima lui sesiune de alergat.) : Acceseaza butonul \n View last run”
Utilizator --> (aplicatia cere accordul utilizatorului de a accesa locatia utilizatorului pentru a calcula distanta alergata\n printr-un pop-up cu messajul “Allow acces to location” si butoanele “Allow” si “Deny”.) : utilizatorul acceseaza \n butonul start new session
Utilizator --> (sesiunea de alergat incepe ) : alege butonul "Allow"\n din pop-up
(sesiunea de alergat incepe ) --> (se afiseaza o fereastra  pe pagina cu \n locatia actuala pe o harta, cronometru ,distanta parcursa si butonul "end session".)

Utilizator --> (se vor afisa statisticile finale despre sesiune si avansul pe care acesta la facut in rank, iar leaderboardul se va actualiza automat) : Acceseaza butonul end session

Utilizator --> (se va da refresh la pagina si nu va incepe sesiunea de alergat.) : utilizatorul alege butonul Deny

Utilizator --> (Se afiseaza  homepage) : Acceseaza butonul home

Utilizator-->(Se  afiseaza o pagina cu toate sesiunile utilizatorului de sport de pe contul logat \n care are optiunea de a filtra datele in legatura cu sesiunile de sport): Acceseaza buttonul My runs

Utilizator --> (se afiseaza pagina “Profile” care contine un tabel cu date ale contului utilizatorului \n precum numele de utilizator , emailul si data in care contul a fost creat) :  acceseaza buttonul “Profile” din navbar

@enduml