@startuml
'https://plantuml.com/class-diagram

class Homepage{
status open/closed
Imagine fundal

}

class Leaderboard{
Afiseaza Utilizator()
}
class Utilizator {
}


class Navbar{
inaltime
latime
culoare
status_butoane activ/inactiv
Ajuta_la_navigare()

}

class Formular_login{
memoreaza_informatiile()
}

class Formular_sign_up{
Memoreaza_informatiile()
}

class Campul_username{
nr_maxim_caractere
dimensiune_x
dimensiune_y
username
afiseaza()
memoreaza_input()
delete_username()
limiteaza_nr_caractere()
}

class Campul_password{
Memoreaza_Input()
}


class Button_Login {
Transmite_informatia()
}


class Rankul_utilizatorului{
Distanta_alergata_totala
Afiseaza_distanta_alergata_totala()
}

class Ultima_Sesiune_de_sport{
informatii_sesiune_alergat
Afiseaza_informatii_ultima_sesiune()
}

class Buttonul_viewLastRun{
Latime
Inaltime
Culoare
Status activ/inactiv
}




class DIV_Sesiune_de_alergat{
dimensiune_x
dimensiune_y
Fundal_Harta
Inregistreaza_informatia_sesiune()
}


class Buttonul_startNewSession{
}

class Mesaj_rosu{
}



class Pop_up_Locatie {
pozitie_x
pozitie_y
afiseaza()
}

class Buttonul_Allow {
}

class Buttonul_Deny{
}


class Locatia_actuala {
}


class Cronometru {
}

class Distanta_parcursa {
}

class Buttonul_end_session {
}

class Statisticile_finale {
}

class Avans_in_rank {
}

class Buttonul_Home {
}

class Buttonul_MyRuns {
}

class Buttonul_Profile {
}

class Pagina_Sesiuni_Alergat {
}

class filtru {
}

class Homepage {
}

class Mesaj_register {
}

class Harta {
}





class Pagina_Profile {
}

class Tabel_cu_date {
}







Homepage "1"*-- "1" Leaderboard
Homepage "1"*-- "1"Navbar
Navbar "1"*-- "1"Formular_login
Navbar "1"*-- "1"Mesaj_register
Mesaj_register "1"*-- "1"Formular_sign_up
Leaderboard"1" o-- "many"Utilizator


Formular_login"1" *--"1" Campul_username
Formular_login"1" *-- "1"Campul_password
Formular_login "1"*-- "1"Button_Login
Formular_login "1"*-- "1"Mesaj_rosu




Homepage "1"*-- "1"Rankul_utilizatorului
Homepage "1"*-- "1"Ultima_Sesiune_de_sport
Ultima_Sesiune_de_sport"1" *-- "1"Buttonul_viewLastRun
Homepage"1" *--"1" Buttonul_viewLastRun
Homepage"1" *-- "1"Buttonul_startNewSession

Buttonul_viewLastRun"1" o-- "1"Pop_up_Locatie

Buttonul_startNewSession "1" o-- "1"Pop_up_Locatie

Pop_up_Locatie "1"*-- "1"Buttonul_Allow
Pop_up_Locatie "1"*-- "1"Buttonul_Deny

Buttonul_Allow  o.. DIV_Sesiune_de_alergat

DIV_Sesiune_de_alergat "1"*-- "1"Harta
Harta"1" *-- "1"Locatia_actuala
DIV_Sesiune_de_alergat "1"*-- "1"Cronometru
DIV_Sesiune_de_alergat "1"*-- "1"Distanta_parcursa
DIV_Sesiune_de_alergat"1" *-- "1"Buttonul_end_session
Buttonul_end_session "1" o-- "1"Statisticile_finale
Buttonul_end_session"1" o--"1" Avans_in_rank

Navbar"1" *--"1" Buttonul_Home
Navbar "1"*-- "1"Buttonul_MyRuns
Navbar"1" *-- "1"Buttonul_Profile
Buttonul_MyRuns  o.. Pagina_Sesiuni_Alergat
Pagina_Sesiuni_Alergat"1" *--"1" filtru
Buttonul_Home o.. Homepage
Buttonul_Profile o.. Pagina_Profile
Pagina_Profile *-- Tabel_cu_date







@enduml